language: node_js
node_js: node
before_install:
  - apt-get update
  - apt-get install nodejs -y
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - apt-get install yarn -y
  - yarn --version
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master
